# Generated by Django 2.0.6 on 2018-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonmenLogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
