# Generated by Django 2.0.6 on 2018-08-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonmenLogin', '0002_auto_20180812_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saveCount', models.IntegerField()),
            ],
        ),
    ]
