# Generated by Django 2.0.6 on 2018-08-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonmenLogin', '0004_auto_20180821_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savecounter',
            old_name='countId',
            new_name='uniqueId',
        ),
        migrations.AlterField(
            model_name='savecounter',
            name='saveCount',
            field=models.IntegerField(default=0),
        ),
    ]
